### ISSUE TITLE
unknown hardware platform Error on RPi Zero W

### ISSUE THREAD

**Issue by SkipHarv** [juergenpabel/HAL9000-installer#1]
Tried manual installation and through the installer. Still getting 
Detecting system configuration...
ERROR: unknown hardware platform, please add mapping to this script and run again

'#############################################################
#                     HAL9000 Installer                     #
#############################################################
Detecting system configuration...
ERROR: unknown hardware platform, please add mapping to this script and run again'

**Comment by juergenpabel** [comment]
Hi, 

I have two questions:
1) What is the output of `uname -m` on your RPi?
2) I presume you're installing on a RPi Zero**2** W (instead of RPi Zero**1** W)? 
Regards
Jürgen

**Comment by SkipHarv** [comment]
It's actually the Zero W 1. Not supported?

**Comment by juergenpabel** [comment]
No - because it doesn't support 64bit mode (and is a bit too slow for real life usage).
